application/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from application.views import CreateApplicationView

app_name = 'application'

urlpatterns = [
    path('create/<int:pkc>', CreateApplicationView.as_view(), name='create-application'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

child/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from child.views import CreateChildView, ListChildView, UpdateChildView, DeleteChildView, DetailChildView

app_name = 'child'

urlpatterns = [
    path('create', CreateChildView.as_view(), name='create-child'),
    path('list', ListChildView.as_view(), name='list-child'),
    path('update/<int:pk>', UpdateChildView.as_view(), name='update-child'),
    path('delete/<int:pk>', DeleteChildView.as_view(), name='delete-child'),
    path('detail/<int:pk>', DetailChildView.as_view(), name='detail-child')
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from config.views import HomeView, AboutView
from config.views import notification

from user.views import signup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('about', AboutView.as_view(), name='about'),
    path('notification', notification, name='notification'),
    path('signup', signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
    path('child/', include('child.urls')),
    path('vaccine/', include('vaccine.urls')),
    path('application/', include('application.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

user/urls.py
from django.urls import path
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from user.views import *

app_name = 'user'

urlpatterns = [
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

child/models.py
from django.db import models

from django.contrib.auth.models import User

from vaccine.models import Dose, Schedule

# Create your models here.
class Child(models.Model):

    GENDERS = (
        ("Male", "Male"),
        ("Female", "Female")
    )

    name = models.CharField(max_length=255)
    gender = models.CharField(max_length=255, choices=GENDERS)
    photo = models.ImageField(null=True, blank=True, upload_to='images/child/')
    date_of_birth = models.DateField()
    place_of_birth = models.TextField()
    place_of_vaccination = models.TextField()
    parent = models.ForeignKey(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        created = not self.pk
        super().save(*args, **kwargs)
        if created:
            for dose in Dose.objects.all():
                if dose.compulsory_after_birth == True:
                    Schedule.objects.create(
                        dose=dose,
                        child=self,
                    )

    def __str__(self):
        return str(self.name)

child/forms.py
from django import forms

from child.models import Child


class CreateChildForm(forms.ModelForm):
    class Meta:
        model = Child
        exclude = ('parent',)
        widgets = {
            'place_of_birth': forms.Textarea(attrs={'rows': 1}),
            'place_of_vaccination': forms.Textarea(attrs={'rows': 1})
        }


class UpdateChildForm(forms.ModelForm):
    class Meta:
        model = Child
        exclude = ('parent',)
        widgets = {
            'place_of_birth': forms.Textarea(attrs={'rows': 1}),
            'place_of_vaccination': forms.Textarea(attrs={'rows': 1})
        }

child/views.py
from django.shortcuts import reverse

from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from child.models import Child
from child.forms import CreateChildForm, UpdateChildForm

from vaccine.models import Vaccine, Dose, Schedule


# Create your views here.
@method_decorator(login_required, name='dispatch')
class CreateChildView(CreateView):
    form_class = CreateChildForm
    template_name = 'child/create.html'

    def form_valid(self, form):
        child = form.save(commit=False)
        child.parent = self.request.user
        return super(CreateChildView, self).form_valid(form)

    def get_success_url(self):
        return reverse('child:list-child')


@method_decorator(login_required, name='dispatch')
class ListChildView(ListView):
    model = Child
    template_name = 'child/list.html'
    context_object_name = 'children'


@method_decorator(login_required, name='dispatch')
class UpdateChildView(UpdateView):
    model = Child
    form_class = UpdateChildForm
    template_name = 'child/update.html'
    context_object_name = 'child'

    def get_success_url(self):
        return reverse('child:list-child')


@method_decorator(login_required, name='dispatch')
class DeleteChildView(DeleteView):
    model = Child
    template_name = 'child/delete.html'
    context_object_name = 'child'

    def get_success_url(self):
        return reverse('child:list-child')


@method_decorator(login_required, name='dispatch')
class DetailChildView(DetailView):
    model = Child
    template_name = 'child/detail.html'
    context_object_name = 'child'

    def get_context_data(self, **kwargs):
        context = super(DetailChildView, self).get_context_data(**kwargs)
        schedules = Schedule.objects.filter(child=self.object)
        vaccines = []
        for vaccine in Vaccine.objects.all():
            for schedule in schedules:
                if vaccine == schedule.dose.vaccine:
                    vaccines.append(vaccine)
        vaccines = list(set(vaccines))
        context['schedules'] = schedules
        context['vaccines']= vaccines
        return context

child/templates/child/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="background container-fluid p-5">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="row">
            <div class="col-md-12">
                <br>
                <h3>Add New Child</h3>
                <hr>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-info btn-block" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

child/templates/child/delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="background container-fluid p-5">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="row">
            <div class="col-md-12">
                <br>
                <h3>Remove {{child}}'s Information</h3>
                <hr>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h5>Are you share to remove your child {{object}}'s information?</h5>
                    <button class="btn btn-info btn-block" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

child/templates/child/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="background container-fluid p-5">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="row p-3">
            <div class="col-md-3 d-flex justify-content-center">
                {% if child.photo %}
                <img src="{{child.photo.url}}" class="rounded" width="100%" height="300">
                {% else %}
                <img src="{% static 'images/default-person.png' %}" class="rounded" width="100%" height="250">
                {% endif %}
            </div>
            <div class="col-md-9">
                <div class="row"><a href="{% url 'child:detail-child' child.id %}"><h3 class="text-dark">
                    {{child.name}}</h3></a></div>
                <div class="row">{% if child.gender == 'Male' %}<i class="fa fa-mars blue-icon"></i>{% else %}<i
                        class="fa fa-venus blue-icon"></i>{% endif %}&nbsp;<h6>{{child.gender}}</h6></div>
                <hr>
                <div class="row">
                    <div class="col px-0">
                        <h6>Birth Details:</h6>
                    </div>
                    <div class="col">
                        <i class="fa fa-calendar blue-icon"></i>&nbsp;{{child.date_of_birth}}
                    </div>
                    <div class="col">
                        <i class="fa fa-map-marker blue-icon"></i>&nbsp;{{child.place_of_birth}}
                    </div>
                </div>
                <hr>
                <div class="row"><b><i class="fa fa-tint blue-icon"></i>&nbsp;Place of Vaccination:</b>&nbsp;{{child.place_of_vaccination}}
                </div>
                <hr>
                <div class="row">
                    <a class="btn btn-info text-light border border-info rounded-pill px-3 py-2" role="button"
                       href="{% url 'child:update-child' child.id %}">Update</a>&nbsp;&nbsp;
                    <a class="btn btn-success text-light border border-success rounded-pill px-3 py-2" role="button"
                       href="{% url 'application:create-application' pkc=child.id %}">Apply for Vaccine</a>&nbsp;&nbsp;
                    <a class="btn btn-danger text-light border border-danger rounded-pill px-3 py-2" role="button"
                       href="{% url 'child:delete-child' child.id %}">Delete</a></div>
                <hr>
                <div class="row p-3">
                    <h4>Vaccines Received</h4>
                </div>
                <ul>
                    {% for vaccine in vaccines %}
                    <li>{{vaccine}}</li>
                    {% endfor %}
                </ul>
                <hr>
                <div class="row p-3">
                    <h4>Timeline</h4>
                </div>
                <div class="row p-3">
                    {% for schedule in schedules reversed %}
                    <div class="col-md-12 border border-dark p-5">
                        <div class="row"><h3 class="text-dark">{{schedule.dose}} for {{schedule.child}}</h3></div>
                        <hr>
                        {% if schedule.vaccinated %}
                        <div class="row"><b><i class="fa fa-calendar blue-icon"></i>&nbsp;Date of Vaccination:</b>&nbsp;{{schedule.date_of_vaccination}}
                        </div>
                        {% else %}
                        <div class="row">
                            <i class="fa fa-calendar blue-icon"></i>&nbsp;&nbsp;
                            <i>
                                {% if schedule.get_status.0 == 'Yellow' %}
                                {{schedule.get_status.1}} days remaining for first day of vaccination
                                <i class="fa fa-circle text-warning"></i>
                                {% elif schedule.get_status.0 == 'Green' %}
                                {{schedule.get_status.1}} days remaining for last day of vaccination
                                <i class="fa fa-circle text-success"></i>
                                {% elif schedule.get_status.0 == 'Red' %}
                                {{schedule.get_status.1}} days have passed and still unvaccinated
                                <i class="fa fa-circle text-danger"></i>
                                {% else %}
                                {% endif %}
                            </i>&nbsp;&nbsp;&nbsp;
                        </div>
                        {% endif %}
                    </div>
                    <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
        <hr>
    </div>
</div>
{% endblock %}

child/templates/child/list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="background container-fluid p-5">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        {% for child in children reversed %}
        {% if child.parent == request.user %}
        <div class="row p-3">
            <div class="col-md-3 d-flex justify-content-center">
                {% if child.photo %}
                <img src="{{child.photo.url}}" class="rounded" width="100%" height="300">
                {% else %}
                <img src="{% static 'images/default-person.png' %}" class="rounded" width="100%" height="250">
                {% endif %}
            </div>
            <div class="col-md-9">
                <div class="row"><a href="{% url 'child:detail-child' child.id %}"><h3 class="text-dark">
                    {{child.name}}</h3></a></div>
                <div class="row">{% if child.gender == 'Male' %}<i class="fa fa-mars blue-icon"></i>{% else %}<i
                        class="fa fa-venus blue-icon"></i>{% endif %}&nbsp;<h6>{{child.gender}}</h6></div>
                <hr>
                <div class="row">
                    <div class="col px-0">
                        <h6>Birth Details:</h6>
                    </div>
                    <div class="col">
                        <i class="fa fa-calendar blue-icon"></i>&nbsp;{{child.date_of_birth}}
                    </div>
                    <div class="col">
                        <i class="fa fa-map-marker blue-icon"></i>&nbsp;{{child.place_of_birth}}
                    </div>
                </div>
                <hr>
                <div class="row"><b><i class="fa fa-tint blue-icon"></i>&nbsp;Place of Vaccination:</b>&nbsp;{{child.place_of_vaccination}}
                </div>
                <hr>
                <div class="row">
                    <a class="btn btn-info text-light border border-info rounded-pill px-3 py-2" role="button"
                       href="{% url 'child:update-child' child.id %}">Update</a>&nbsp;&nbsp;
                    <a class="btn btn-info text-light border border-info rounded-pill px-3 py-2" role="button"
                       href="{% url 'child:detail-child' child.id %}">Detail</a>&nbsp;&nbsp;
                    <a class="btn btn-success text-light border border-success rounded-pill px-3 py-2" role="button"
                       href="{% url 'application:create-application' pkc=child.id %}">Apply for Vaccine</a>&nbsp;&nbsp;
                    <a class="btn btn-danger text-light border border-danger rounded-pill px-3 py-2" role="button"
                       href="{% url 'child:delete-child' child.id %}">Delete</a></div>
            </div>
        </div>
        <hr>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

child/templates/child/update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="background container-fluid p-5">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="row">
            <div class="col-md-12">
                <br>
                <h3>Update {{child}}'s Information</h3>
                <hr>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-info btn-block" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}