child/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from child.views import CreateChildView, ListChildView, UpdateChildView, DeleteChildView, DetailChildView

app_name = 'child'

urlpatterns = [
    path('create', CreateChildView.as_view(), name='create-child'),
    path('list', ListChildView.as_view(), name='list-child'),
    path('update/<int:pk>', UpdateChildView.as_view(), name='update-child'),
    path('delete/<int:pk>', DeleteChildView.as_view(), name='delete-child'),
    path('detail/<int:pk>', DetailChildView.as_view(), name='detail-child')
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from config.views import HomeView, AboutView
from config.views import notification

from user.views import signup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('about', AboutView.as_view(), name='about'),
    path('notification', notification, name='notification'),
    path('signup', signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
    path('child/', include('child.urls')),
    path('vaccine/', include('vaccine.urls')),
    path('application/', include('application.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

user/urls.py
from django.urls import path
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from user.views import *

app_name = 'user'

urlpatterns = [
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

vaccine/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from vaccine.views import ListScheduleView, VaccinatedListScheduleView, UnvaccinatedListScheduleView
from vaccine.views import UpdateScheduleView

app_name = 'vaccine'

urlpatterns = [
    path('schedule/list', ListScheduleView.as_view(), name='list-schedule'),
    path('schedule/list/vaccinated', VaccinatedListScheduleView.as_view(), name='vaccinated-list-schedule'),
    path('schedule/list/unvaccinated', UnvaccinatedListScheduleView.as_view(), name='unvaccinated-list-schedule'),
    path('schedule/update/<int:pk>', UpdateScheduleView.as_view(), name='update-schedule'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="background container-fluid p-5">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="row p-3 justify-content-center">
            <h1>Our Vaccines</h1>
        </div>
        <hr>
        <div class="row p-3">
        {% for vaccine in vaccines %}
            <div class="col-md-6 border border-dark p-5">
                <div class="row justify-content-center"><h3 class="text-dark">{{vaccine.name}}</h3></div>
                <div class="row justify-content-center"><p>{{vaccine.description}}</p></div>
                <div class="row justify-content-center"><p><b>Route: </b>{{vaccine.route}}</p></div>
                <div class="row justify-content-center"><p><b>Side Effects: </b>{{vaccine.side_effects}}</p></div>
                <div class="row justify-content-center"><p><b>Before Care: </b>{{vaccine.before_care}}</p></div>
                <div class="row justify-content-center"><p><b>After Care: </b>{{vaccine.after_care}}</p></div>
                <div class="row justify-content-center"><p><b>Protect Against: </b>{{vaccine.protect_against}}</p></div>
            </div>
        <hr>
        {% endfor %}
        </div>
    </div>
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="row p-3 justify-content-center">
            <h1>Contraindication of all immunization</h1>
        </div>
        <hr>
        <div class="row p-3">
            <ul class="border border-dark p-5">
                <li>Child has a high fever.</li>
                <li>Child has had a bad reaction with previous immunization.</li>
                <li>Child has had, or is having treatment for cancer.</li>
                <li>Child is taking any medicine which affects the immune system, for eg: immunosuppressant( given after organ transplant or for malignant disease) or high dose steroids.</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Theme Made By www.w3schools.com - No Copyright -->
    <title>Immunation</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-dark navbar-expand-md bg-info">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}"><i class="fa fa-tint fa-2x"></i></a>
        <a class="navbar-brand" href="{% url 'home' %}">IMMUNATION</a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="nav navbar-nav text-center">
                <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false"
                       href="#">Children</a>
                    <div class="dropdown-menu text-center">
                        <a class="dropdown-item" href="{% url 'child:create-child' %}">Add new Child</a>
                        <hr>
                        <a class="dropdown-item" href="{% url 'child:list-child' %}">List of your Children</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false"
                       href="#">Schedule</a>
                    <div class="dropdown-menu text-center">
                        <a class="dropdown-item" href="{% url 'vaccine:list-schedule' %}">All schedule</a>
                        <hr>
                        <a class="dropdown-item" href="{% url 'vaccine:vaccinated-list-schedule' %}">Vaccinated</a>
                        <hr>
                        <a class="dropdown-item" href="{% url 'vaccine:unvaccinated-list-schedule' %}">Unvaccinated</a>
                    </div>
                </li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
            </ul>
            <span class="navbar-text ml-auto d-flex justify-content-center">
                {% if user.is_authenticated %}
                <a class="btn btn-light text-dark" role="button" href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a class="btn btn-light text-dark" role="button" href="{% url 'login' %}">Log In</a>
                &nbsp;
                <a class="btn btn-light text-dark" role="button" href="{% url 'signup' %}">Signup</a>
                {% endif %}
            </span>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
<!-- Footer -->
<footer class="text-center text-lg-start">
  <br>
  <!-- Section: Links  -->
  <section class="border-top">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-6 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>University Name
          </h6>
          <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis esse expedita molestias nesciunt nobis quae repellendus, reprehenderit sunt totam vel. Asperiores doloribus illum magnam molestiae nesciunt nulla perspiciatis quae voluptas.
          </p>
        </div>
        <!-- Grid column -->


        <!-- Grid column -->
        <div class="col-md-6 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fa fa-home me-3"></i> New Delhi, India</p>
          <p>
            <i class="fa fa-envelope me-3"></i>
            youremail@gmail.com
          </p>
          <p><i class="fa fa-phone me-3"></i> + 977 234 567 88</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="#">OfficeName</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid p-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{% static 'images/main_picture.jpg' %}" class="img-responsive" width="100%">
        </div>
        <div class="col-md-6">
            <div class="container-fluid px-0 text-center">
                <div class="jumbotron py-5">
                    <br><br>
                    <h1>Welcome to Immunation!</h1>
                    <br>
                    <p>Immunization is a proven tool for controlling and eliminating life-threatening
                        infectious diseases and is estimated to avert between 2 and 3 million deaths each year but an
                        estimated 18.7 million infants worldwide are still missing out on basic vaccines.</p>
                    <p>-World Health Organization</p>
                    <br>
                    {% if not request.user.is_authenticated %}
                    <a class="btn btn-info text-light border border-info rounded-pill px-5 py-2" role="button" href="{% url 'signup' %}">Join Now</a>
                    &nbsp;&nbsp;
                    {% endif %}
                    <a class="btn btn-info text-light border border-info rounded-pill px-5 py-2" role="button" href="{% url 'about' %}">About</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/notification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
The notifications have been sent.
</body>
</html>