config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from config.views import HomeView, AboutView
from config.views import notification

from user.views import signup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('about', AboutView.as_view(), name='about'),
    path('notification', notification, name='notification'),
    path('signup', signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
    path('child/', include('child.urls')),
    path('vaccine/', include('vaccine.urls')),
    path('application/', include('application.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

user/urls.py
from django.urls import path
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from user.views import *

app_name = 'user'

urlpatterns = [
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

vaccine/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config.settings import MEDIA_URL, MEDIA_ROOT

from vaccine.views import ListScheduleView, VaccinatedListScheduleView, UnvaccinatedListScheduleView
from vaccine.views import UpdateScheduleView

app_name = 'vaccine'

urlpatterns = [
    path('schedule/list', ListScheduleView.as_view(), name='list-schedule'),
    path('schedule/list/vaccinated', VaccinatedListScheduleView.as_view(), name='vaccinated-list-schedule'),
    path('schedule/list/unvaccinated', UnvaccinatedListScheduleView.as_view(), name='unvaccinated-list-schedule'),
    path('schedule/update/<int:pk>', UpdateScheduleView.as_view(), name='update-schedule'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

vaccine/models.py
from django.db import models

import datetime

# Create your models here.
class Vaccine(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    route = models.TextField(blank=True, null=True)
    site = models.TextField(blank=True, null=True)
    side_effects = models.TextField(blank=True, null=True)
    before_care = models.TextField(blank=True, null=True)
    after_care = models.TextField(blank=True, null=True)
    protect_against = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.name)


class Dose(models.Model):
    UNITS = (
        ('ml', 'ml'),
        ('drop', 'drop')
    )
    vaccine = models.ForeignKey(Vaccine, on_delete=models.CASCADE)
    number = models.PositiveIntegerField()
    quantity = models.DecimalField(max_digits=5, decimal_places=2)
    unit = models.CharField(max_length=255, choices=UNITS)
    first_day_from_birth = models.PositiveIntegerField()
    last_day_from_birth = models.PositiveIntegerField()
    booster = models.BooleanField(default=False)
    compulsory_after_birth = models.BooleanField(default=False)

    def __str__(self):
        return str(self.vaccine) + " dose " + str(self.number)


class Schedule(models.Model):
    dose = models.ForeignKey(Dose, on_delete=models.CASCADE)
    child = models.ForeignKey('child.Child', on_delete=models.CASCADE)
    date_of_vaccination = models.DateField(blank=True, null=True)
    vaccinated = models.BooleanField(default=False)

    def get_status(self):
        if datetime.date.today() < self.child.date_of_birth + datetime.timedelta(days=self.dose.first_day_from_birth):
            time_delta_value = self.child.date_of_birth + datetime.timedelta(days=self.dose.first_day_from_birth) - datetime.date.today()
            days_remaining = time_delta_value.days
            return ["Yellow", days_remaining]
        elif datetime.date.today() >= self.child.date_of_birth + datetime.timedelta(days=self.dose.first_day_from_birth) and datetime.date.today() < self.child.date_of_birth + datetime.timedelta(days=self.dose.last_day_from_birth):
            time_delta_value = self.child.date_of_birth + datetime.timedelta(days=self.dose.last_day_from_birth) - datetime.date.today()
            days_remaining = time_delta_value.days
            return ["Green", days_remaining]
        else:
            time_delta_value = datetime.date.today() - (self.child.date_of_birth + datetime.timedelta(days=self.dose.last_day_from_birth))
            days_passed = time_delta_value.days
            return ["Red", days_passed]


    def __str__(self):
        return str(self.child) + "'s vaccination for " + str(self.dose)

vaccine/forms.py
from django import forms

from vaccine.models import Schedule


class UpdateScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['vaccinated']

vaccine/views.py
from django.shortcuts import reverse

from django.views.generic import ListView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from datetime import date

from vaccine.models import Schedule
from vaccine.forms import UpdateScheduleForm


# Create your views here.
@method_decorator(login_required, name='dispatch')
class ListScheduleView(ListView):
    model = Schedule
    template_name = 'schedule/list.html'
    context_object_name = 'schedules'


@method_decorator(login_required, name='dispatch')
class VaccinatedListScheduleView(ListView):
    model = Schedule
    template_name = 'schedule/vaccinated_list.html'
    context_object_name = 'schedules'


@method_decorator(login_required, name='dispatch')
class UnvaccinatedListScheduleView(ListView):
    model = Schedule
    template_name = 'schedule/unvaccinated_list.html'
    context_object_name = 'schedules'


@method_decorator(login_required, name='dispatch')
class UpdateScheduleView(UpdateView):
    model = Schedule
    form_class = UpdateScheduleForm
    template_name = 'schedule/update.html'
    context_object_name = 'schedule'

    def form_valid(self, form):
        schedule = form.save(commit=False)
        if schedule.vaccinated:
            schedule.date_of_vaccination = date.today()
        return super(UpdateScheduleView, self).form_valid(form)

    def get_success_url(self):
        return reverse('vaccine:vaccinated-list-schedule')

vaccine/templates/schedule/list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="background container-fluid p-5">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="row p-3">
        {% for schedule in schedules reversed %}
        {% if schedule.child.parent == request.user %}
            <div class="col-md-6 border border-dark p-5">
                <div class="row"><h3 class="text-dark">{{schedule.dose}} for {{schedule.child}}</h3></div>
                <hr>
                <div class="row"><b><i class="fa fa-calendar blue-icon"></i>&nbsp;Date of Vaccination:</b>&nbsp;{{schedule.date_of_vaccination}}</div>
            </div>
        <hr>
        {% endif %}
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

vaccine/templates/schedule/unvaccinated_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="background container-fluid p-5">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="row p-3">
            {% for schedule in schedules reversed %}
            {% if schedule.child.parent == request.user and not schedule.vaccinated %}
            <div class="col-md-6 border border-dark p-5">
                <div class="row"><h3 class="text-dark">{{schedule.dose}} for {{schedule.child}}</h3>
                </div>
                <hr>
                <div class="row">
                    <i class="fa fa-calendar blue-icon"></i>&nbsp;&nbsp;
                    <i>
                        {% if schedule.get_status.0 == 'Yellow' %}
                        {{schedule.get_status.1}} days remaining for first day of vaccination
                        <i class="fa fa-circle text-warning"></i>
                        {% elif schedule.get_status.0 == 'Green' %}
                        {{schedule.get_status.1}} days remaining for last day of vaccination
                        <i class="fa fa-circle text-success"></i>
                        {% elif schedule.get_status.0 == 'Red' %}
                        {{schedule.get_status.1}} days have passed and still unvaccinated
                        <i class="fa fa-circle text-danger"></i>
                        {% else %}
                        {% endif %}
                    </i>&nbsp;&nbsp;&nbsp;
                </div>
                <hr>
                <div class="row">
                    <a class="btn btn-success text-light border border-success rounded-pill px-3 py-2" role="button"
                       href="{% url 'vaccine:update-schedule' schedule.id %}">Mark Vaccinated</a></div>
            </div>
            <hr>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

vaccine/templates/schedule/update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="background container-fluid p-5">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="row">
            <div class="col-md-12">
                <br>
                <h3>Mark {{schedule.child}} as vaccinated</h3>
                <hr>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-info btn-block" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

vaccine/templates/schedule/vaccinated_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="background container-fluid p-5">
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <div class="row p-3">
            {% for schedule in schedules reversed %}
            {% if schedule.child.parent == request.user and schedule.vaccinated %}
            <div class="col-md-6 border border-dark p-5">
                <div class="row"><h3 class="text-dark">{{schedule.dose}} for {{schedule.child}}</h3>
                </div>
                <hr>
                <div class="row"><b><i class="fa fa-calendar blue-icon"></i>&nbsp;Date of Vaccination:</b>&nbsp;{{schedule.date_of_vaccination}}
                </div>
            </div>
            <hr>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}